[project]
name = "semantic-kernel-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "npx>=0.1.6",
    "semantic-kernel[mcp]>=1.35.1",
]
